# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
                ('plural', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='ArtTeilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='ArtVeranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
                ('teilnahmearten', models.ManyToManyField(to='Wettbewerbe.ArtTeilnahme')),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wettbewerbe.ArtTeilnahme')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wettbewerbe.Person')),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Unterseite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
                ('template_name', models.CharField(blank=True, max_length=40, null=True)),
                ('gehoert_zu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.Unterseite')),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.ArtVeranstaltung')),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='WettbewerbsKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('datum_erstellt', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.TextField()),
                ('art_kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.ArtKategorie')),
                ('gehoert_zu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.WettbewerbsKategorie')),
            ],
            options={
                'abstract': False,
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='gehoert_zu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.WettbewerbsKategorie'),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='veranstaltung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wettbewerbe.Veranstaltung'),
        ),
        migrations.AddField(
            model_name='person',
            name='veranstaltungen',
            field=models.ManyToManyField(through='Wettbewerbe.Teilnahme', to='Wettbewerbe.Veranstaltung'),
        ),
    ]
