# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wettbewerbe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artkategorie',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.RenameField(
            model_name='artteilnahme',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.RenameField(
            model_name='artveranstaltung',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.RenameField(
            model_name='teilnahme',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.RenameField(
            model_name='unterseite',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.RenameField(
            model_name='veranstaltung',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.RenameField(
            model_name='wettbewerbskategorie',
            old_name='datum_erstellt',
            new_name='zeit_erstellt',
        ),
        migrations.AddField(
            model_name='artkategorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='artkategorie',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artteilnahme',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='artteilnahme',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artveranstaltung',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='artveranstaltung',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nutzer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unterseite',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='unterseite',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wettbewerbskategorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='wettbewerbskategorie',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
