# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0002_auto_20170311_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artkategorie',
            options={'verbose_name_plural': 'Arten der Wettbewerbskategorien'},
        ),
        migrations.AlterModelOptions(
            name='artteilnahme',
            options={'verbose_name_plural': 'Arten der Teilnahme'},
        ),
        migrations.AlterModelOptions(
            name='artveranstaltung',
            options={'verbose_name_plural': 'Arten der Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='teilnahme',
            options={'verbose_name_plural': 'Konkrete Teilnahmen'},
        ),
        migrations.AlterModelOptions(
            name='unterseite',
            options={'verbose_name_plural': 'Unterseiten'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='wettbewerbskategorie',
            options={'verbose_name_plural': 'Wettbewerbskategorien'},
        ),
    ]
