# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0003_auto_20170311_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artteilnahme',
            options={'verbose_name_plural': 'Teilnahmearten'},
        ),
        migrations.AlterModelOptions(
            name='teilnahme',
            options={'verbose_name': 'Konkrete Teilnahme', 'verbose_name_plural': 'Konkrete Teilnahmen'},
        ),
        migrations.AlterModelOptions(
            name='wettbewerbskategorie',
            options={'verbose_name': 'Wettbewerbskategorie', 'verbose_name_plural': 'Wettbewerbskategorien'},
        ),
        migrations.RemoveField(
            model_name='teilnahme',
            name='bezeichnung',
        ),
        migrations.RemoveField(
            model_name='teilnahme',
            name='slug',
        ),
        migrations.AlterField(
            model_name='person',
            name='nutzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
