# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0005_teilnahme_nur_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artteilnahme',
            options={'verbose_name': 'Teilnahmeart', 'verbose_name_plural': 'Teilnahmearten'},
        ),
        migrations.AlterModelOptions(
            name='artveranstaltung',
            options={'verbose_name': 'Art von Veranstaltungen', 'verbose_name_plural': 'Arten von Veranstaltungen'},
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wettbewerbe.Person'),
        ),
    ]
