# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0006_auto_20170724_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unterseite',
            name='gehoert_zu',
        ),
        migrations.DeleteModel(
            name='Unterseite',
        ),
    ]
