# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0009_auto_20170804_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teilnahme',
            unique_together=set([('person', 'veranstaltung')]),
        ),
    ]
