# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0010_auto_20170806_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='beschreibung',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='wettbewerbskategorie',
            name='beschreibung',
            field=models.TextField(default=''),
        ),
    ]
