# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0012_artteilnahme_g_hat_teilgenommen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artteilnahme',
            name='g_hat_teilgenommen',
            field=models.CharField(default='', max_length=100, verbose_name='Grammatik: "hat teilgenommen"'),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='art',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wettbewerbe.ArtTeilnahme'),
        ),
    ]
