# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0015_auto_20170830_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wettbewerbskategorie',
            name='gehoert_zu',
        ),
        migrations.AddField(
            model_name='wettbewerbskategorie',
            name='gehoert_zu',
            field=models.ManyToManyField(blank=True, to='Wettbewerbe.WettbewerbsKategorie'),
        ),
    ]
