# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0016_auto_20170830_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wettbewerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeitraum', models.CharField(default='', max_length=100)),
                ('zur_kategrorie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.WettbewerbsKategorie')),
            ],
            options={
                'verbose_name': 'Wettbewerb',
                'verbose_name_plural': 'Wettbewerbe',
            },
        ),
        migrations.CreateModel(
            name='Wettbewerbsjahrgang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('jahrgang', models.SmallIntegerField(default=0)),
                ('wettbewerb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.Wettbewerb')),
            ],
            options={
                'verbose_name': 'Wettbewerbsjahrgang',
                'verbose_name_plural': 'Wettbewerbsjahrgänge',
            },
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='jahrgang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wettbewerbe.Wettbewerbsjahrgang'),
        ),
    ]
