# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0017_auto_20170830_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wettbewerb',
            name='zeitraum',
        ),
        migrations.AddField(
            model_name='wettbewerb',
            name='datum_anfang',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wettbewerb',
            name='datum_ende',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wettbewerbsjahrgang',
            name='_datum_anfang',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wettbewerbsjahrgang',
            name='_datum_ende',
            field=models.DateField(blank=True, null=True),
        ),
    ]
