# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0002_auto_20170311_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutzer',
            options={'verbose_name': 'Nutzer', 'verbose_name_plural': 'Nutzer'},
        ),
    ]
