# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0003_auto_20170507_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutzerprofil',
            name='geschlecht',
            field=models.CharField(choices=[('w', 'weiblich'), ('m', 'männlich'), ('', 'sonstiges')], default='', max_length=1),
        ),
    ]
