# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0004_auto_20170729_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutzerprofil',
            name='geschlecht',
            field=models.CharField(choices=[('w', 'weiblich'), ('m', 'männlich'), (' ', 'sonstiges')], default=' ', max_length=1),
        ),
    ]
