# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehemaliger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('lebenslauf', models.TextField()),
                ('ort', models.CharField(max_length=255)),
                ('taetigkeit', models.CharField(max_length=255, verbose_name='Tätigkeit')),
                ('nutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ehemalige',
            },
        ),
    ]
